# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kxlupgWo41DO2-pZ2QmUXqKEJoSAxkpe
"""

import pandas as pd
from sqlalchemy import create_engine

# 替换为您的 SQLite 数据库文件路径
DATABASE_URI = 'sqlite:///health_events_data.db'

def fetch_data(query, connection_string):
    """使用提供的SQL查询从SQLite数据库中获取数据。"""
    engine = create_engine(connection_string)
    with engine.connect() as connection:
        data = pd.read_sql(query, connection)
    return data

def calculate_missing_values(df):
    """计算每列中缺失单元格的数量。"""
    missing_values = df.isnull().sum()
    return missing_values

def count_categories(df, columns):
    """计算指定列中的类别数量。"""
    category_counts = {column: df[column].nunique() for column in columns}
    return category_counts

def main():
    # 替换为您实际需要查询的SQL
    query = "SELECT * FROM your_table_name"

    # 获取数据
    df = fetch_data(query, DATABASE_URI)

    # 计算缺失值
    missing_values = calculate_missing_values(df)
    print("每列缺失单元格的数量：")
    print(missing_values)

    # 计算指定列中的类别数量
    columns_to_count = ['Condition', 'Agent', 'Reporting Agency', 'City']
    category_counts = count_categories(df, columns_to_count)
    print("\n每列中的类别数量：")
    for column, count in category_counts.items():
        print(f"{column}: {count}")

if __name__ == "__main__":
    main()