# -*- coding: utf-8 -*-
"""lab01_starter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1akh7NDZVfgsajVazdHeS4zeUQS8Ra1eK
"""

!pip install requests
!pip install beautifulsoup4
!pip install lxml

import requests
from bs4 import BeautifulSoup

movie_url = "https://www.boxofficemojo.com/chart/top_lifetime_gross/"
r = requests.get(movie_url)
# r.content (b), r.text
if r.status_code ==200:
    print(r.content)
    print(r.text)

# image fetch from r.content (download jpg)
img_url = "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_SY139_CR1,0,92,139_.jpg"
r = requests.get(img_url)
with open('temp_img.jpg', 'wb') as f:
    f.write(r.content)

# fetch
with open('/content/sample_html.html') as f:
  data = f.read()

soup = BeautifulSoup(data, 'html')

# 'p' 文本内容，'a'超链接/网址
soup.find('table') #find_all()

# find string
soup.find(string = "List Item One").parent.parent

